version: '2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  nginx:
    build:
      context: nginx/
      #args:
      #  - http_proxy=
      #  - HTTP_PROXY=
      #  - https_proxy=
      #  - HTTPS_PROXY=
    ports:
      - "80:80"
    volumes:
      - ./nginx/data:/var/www/data
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5044:5044"
    links:
      - elasticsearch
      - nginx
  filebeat:
    build:
      context: filebeat/
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ./filebeat/log:/log
    links:
      - logstash
  kibana:
    build:
      context: kibana/
    volumes:
       - "./kibana/config/:/etc/kibana/"
    ports:
       - "5601:5601"
    links:
       - elasticsearch
